name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy Backend
      run: |
        echo "Deploying backend..."
        # Здесь будут команды для деплоя backend
        # Например, подключение к серверу и обновление кода
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    
    - name: Deploy Frontend
      run: |
        echo "Deploying frontend..."
        # Здесь будут команды для деплоя frontend
        # Например, сборка и загрузка на хостинг
      env:
        REACT_APP_API_URL: ${{ secrets.API_URL }} 